### ISSUE TITLE
Mysql5.6版本以上limit与order by同时使用出现数据重复问题

### ISSUE THREAD

**Issue by Dev-Flo200** [sanyueruanjian/smpe-admin#38]
### 建议内容
使用框架时要注意limit与order by的同时使用，在5.6版本以上的mysql排序时使用堆排序，堆排序不稳定，会导致具有相同排序字段的数据查询出来后顺序和数据库不一致，分页后出现数据重复的情况

### 实施方案
仅供参考
1. 排序时加上order by id使每一次查询的排序字段都不一样
2. 加索引

**Comment by shiwei-Ren** [comment]
可以将每个需要排序的sql语句在加上根据id排序。大多数情况还是要在具体业务里实现
